Add bert pretraining preprocessing
omniocular/omniocular pull request #25
Opened 2019-06-03 20:52 UTC by Ji-Xin

## Description
 Please include a summary of the change and which issue is fixed.
 
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist
- [x] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Todo
- [ ] Please add WIP tasks in this section
- [ ] Ensure that the pull request title is of the format "WIP: Title" until all of these are checked
- [ ] Remove this section from the pull request description if no pending tasks exist

2019-06-03 21:46 UTC, achyudh commented on datasets/java_top1k/try.py
> +import tqdm
Do we really need this file?

2019-06-03 22:37 UTC, achyudh requested changes
Can you please remove datasets/java_top1k/try.py? It doesn't seem to do anything.

2019-06-04 19:36 UTC, Ji-Xin commented
Deleted

2019-06-04 20:02 UTC, achyudh approved these changes

2019-06-04 20:03 UTC, achyudh commented
LGTM.

2019-06-04 20:03 UTC, merged